# Generated by Django 5.2.3 on 2025-06-19 09:45

import pronunciation_evaluation.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=pronunciation_evaluation.utils.generate_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
